#%RAML 0.8
title: CIOT
version: 1
/user_profile/index:
  get:
  
/v1/streams/new:
  post:
/v1/device/{id}/streams:
  get:
/v1/device/{id}/streams/last:
  get:
/v1/device/{id}/streams/{date}:
  get:
/v1/device/{id}/streams/{start_date}/{end_date}:
  get: